import { definePage } from '../../lib/page-types';
import { P, gbp, pct, t, compute } from '../../lib/kit';

const S = P.sdlt, L = P.lbtt, W = P.ltt;
const FLAT = 220000;
const HOME = 300000;
const homeFirst = t('england', HOME, 'first') + t('england', FLAT, 'additional');
const rentalFirst = t('england', FLAT) + t('england', HOME, 'additional');
const co = (n: 'england' | 'scotland' | 'wales', p: number, relief = true) => compute({ nation: n, price: p, situation: 'additional', company: true, companyRelief: relief }).total;

export default definePage({
  id: 'buy-to-let-stamp-duty',
  group: 'situations',
  order: 10,
  slug: 'buy-to-let-stamp-duty',
  nav: 'Buy-to-let',
  card: `Landlords pay the surcharge in all three nations, personally or through a company, and never get it back.`,
  title: 'Buy-to-Let Stamp Duty 2026: Landlords and Limited Companies',
  description: `Buy-to-let stamp duty in 2026: ${gbp(t('england', FLAT, 'additional'))} on a ${gbp(FLAT)} rental flat in England, ${gbp(t('scotland', FLAT, 'additional'))} in Scotland, ${gbp(t('wales', FLAT, 'additional'))} in Wales, bought personally or via a company.`,
  h1: 'Stamp duty on buy-to-let property',
  intro: 'A rental purchase almost always carries the additional-property surcharge, and unlike a home mover, a landlord has no way to reclaim it.',
  resume: `A landlord who already owns a home and buys a ${gbp(FLAT)} flat to let pays ${gbp(t('england', FLAT, 'additional'))} of SDLT in England or Northern Ireland, because the ${pct(S.higher_rates_surcharge)} higher rates are added to every band from ${gbp(S.higher_rates_min_price)}. The same flat costs ${gbp(t('scotland', FLAT, 'additional'))} in Scotland, where the ${pct(L.ads_rate)} Additional Dwelling Supplement is charged on the whole price, and ${gbp(t('wales', FLAT, 'additional'))} in Wales on the higher-rates table. Buying through a limited company changes nothing at that price: a company pays the surcharge on its very first dwelling in all three nations, and in England it avoids the ${pct(S.corporate_flat_rate)} flat rate above ${gbp(S.corporate_flat_threshold)} by claiming the relief for a property rental business. Someone who owns no home at all and buys a rental pays ordinary rates, ${gbp(t('england', FLAT))} here, but no first-time buyer relief. The surcharge on a rental is never refundable.`,
  faqs: [
    { q: 'I rent my own flat and want to buy a property to let out. Do I pay the higher rates?', a: `Not on this purchase, if you own no other dwelling anywhere in the world. You will own a single dwelling at the end of the day, so SDLT is charged at standard rates: ${gbp(t('england', FLAT))} on a ${gbp(FLAT)} flat. You cannot claim first-time buyer relief, because you will not live there, and the purchase does cost you your first-time buyer status for the future.` },
    { q: 'Is it cheaper in stamp duty to buy a rental through a limited company?', a: `Not at typical prices. In England a company pays the ${pct(S.higher_rates_surcharge)} higher rates on its first flat, exactly like an individual landlord who owns a home: ${gbp(co('england', FLAT))} on ${gbp(FLAT)}. In Scotland the company pays the ADS even when its directors own nothing, and in Wales it pays the higher rates. Company ownership is a decision about income tax and finance, not about purchase tax.` },
    { q: `My buy-to-let company is buying a house for ${gbp(600000)}. Does the ${pct(S.corporate_flat_rate)} rate apply?`, a: `Not if the company claims the relief for a property rental business on the return. With it, the purchase is taxed at the higher rates: ${gbp(co('england', 600000))}. Without a relief, the flat ${pct(S.corporate_flat_rate)} rate on the whole price gives ${gbp(co('england', 600000, false))}. HMRC lists letting to tenants as a qualifying property rental business, and the conveyancer claims the relief on the return itself; no separate application is needed.` },
    { q: 'Can I get the second-home surcharge back if I sell another rental later?', a: `No. The refund exists only when the property you bought replaces your main residence and the old main residence is sold within the time limit: ${S.replace_main_residence_years} years in England, ${L.replace_main_residence_months} months in Scotland and ${W.replace_main_residence_years} years in Wales. Selling one rental after buying another does not qualify, so the ${gbp(compute({ nation: 'england', price: FLAT, situation: 'additional' }).surcharge)} surcharge on a ${gbp(FLAT)} English flat stays paid.` },
    { q: 'Do I pay the non-resident surcharge on a buy-to-let if I live in Dubai?', a: `Yes, in England and Northern Ireland, if you spent fewer than ${S.non_resident_days} days in the UK in the year before completion. The ${pct(S.non_resident_surcharge)} is added on top of the higher rates, so a ${gbp(FLAT)} rental costs ${gbp(t('england', FLAT, 'additional', { nonResident: true }))}. Scotland and Wales have no non-resident surcharge, so a landlord living in the Gulf pays the same in Edinburgh or Cardiff as a resident.` },
  ],
  mini: 'btlOwnership',
  related: ['stamp-duty-second-home', 'stamp-duty-company-purchase', 'additional-dwelling-supplement', 'ltt-higher-rates', 'non-resident-stamp-duty-surcharge', 'commercial-property-stamp-duty'],
  sources: ['govSdltHigher', 'govSdltCorporate', 'rsAds', 'wraHigher', 'sdltmNonResident'],
  body: (h) => {
    const prices = [100000, 150000, 220000, 300000, 450000, 650000];
    const rows = prices.map((p) => [h.gbp(p), h.gbp(h.t('england', p, 'additional')), h.gbp(h.t('scotland', p, 'additional')), h.gbp(h.t('wales', p, 'additional')), h.gbp(h.t('england', p))]);
    const coRows = [150000, 400000, 600000, 1000000].map((p) => [h.gbp(p), h.gbp(co('england', p)), h.gbp(co('england', p, false)), h.gbp(co('scotland', p)), h.gbp(co('wales', p))]);
    return `
<h2>The landlord’s bill in each nation</h2>
<p>Each nation adds its surcharge in a different way, and the gap between them depends on the price. England and Northern Ireland raise every SDLT band by ${h.pct(S.higher_rates_surcharge)}, so even the first ${h.gbp(S.residential[0][0] as number)} is taxed at ${h.pct(S.higher_rates_surcharge)}. Scotland leaves the LBTT bands alone and adds the ADS at ${h.pct(L.ads_rate)} of the full price. Wales replaces the main table with a separate higher-rates table that starts at ${h.pct(W.higher[0][1])} and climbs to ${h.pct(W.higher[W.higher.length - 1][1])}. The result is that a ${h.gbp(100000)} terrace bought to let in Glasgow costs ${h.gbp(h.t('scotland', 100000, 'additional'))}, against ${h.gbp(h.t('england', 100000, 'additional'))} for the same price in Leeds and ${h.gbp(h.t('wales', 100000, 'additional'))} in Swansea.</p>
${h.table(['Price', 'England & NI', 'Scotland', 'Wales', 'England, no other home'], rows, 'Tax on a rental purchase by a landlord who owns another dwelling', ['l', 'r', 'r', 'r', 'r'])}
<p>The last column is the comparison landlords often forget: the same flat bought by someone with no other property. The difference between the two English columns is the surcharge, and it is the price of owning more than one dwelling at the end of completion day. No rental property is too cheap to escape it, except one under ${h.gbp(S.higher_rates_min_price)}, the floor below which neither SDLT higher rates, ADS nor the Welsh higher rates apply.</p>
<h2>Your first rental when you own no home</h2>
<p>Some buyers rent where they work and buy where prices allow, then let the property out. If you own nothing else, that purchase leaves you with one dwelling, so the surcharge does not apply in any nation: you pay ${h.gbp(h.t('england', FLAT))} on a ${h.gbp(FLAT)} English flat, ${h.gbp(h.t('scotland', FLAT))} in Scotland and ${h.gbp(h.t('wales', FLAT))} in Wales. The catch comes on two sides. First-time buyer relief is refused, because the relief requires every buyer to intend to live in the property as their only or main residence; a tenant living there does not count. And the rental makes you a former owner for ever, so when you later buy a home to live in, you will own two dwellings at the end of that day and pay the higher rates on your own home. Selling the rental later does not refund that surcharge, because the rental was never your main residence.</p>
<p>The order of purchases therefore matters. Take a buyer in England planning a ${h.gbp(HOME)} home and a ${h.gbp(FLAT)} rental. Home first, with the ${h.a('stamp-duty-first-time-buyer', 'first-time buyer relief')}, then the rental at the higher rates: ${h.gbp(homeFirst)} in total. Rental first at standard rates, then the home at the higher rates: ${h.gbp(rentalFirst)}. The mini-simulator above shows the two rental bills; the ${h.a('stamp-duty-second-home', 'second home guide')} covers the home purchase that follows.</p>
<h2>Buying through a limited company</h2>
<p>A company is not a person with a home, so the tax authorities treat its first purchase as if it already owned one. All three nations charge their surcharge on a company’s purchase of a dwelling from ${h.gbp(S.higher_rates_min_price)}, with no exception for a newly formed special purpose vehicle.</p>
${h.table(['Price', 'England, rental relief', 'England, no relief', 'Scotland', 'Wales'], coRows, 'Company purchase of a dwelling, computed with the 2026 rates', ['l', 'r', 'r', 'r', 'r'])}
<h3>England and Northern Ireland: the ${h.pct(S.corporate_flat_rate)} rate</h3>
<p>Above ${h.gbp(S.corporate_flat_threshold)}, a company buying a dwelling pays ${h.pct(S.corporate_flat_rate)} of the entire price unless it qualifies for a relief. The reliefs listed by HMRC include a property rental business letting to unconnected tenants, property developers and traders, properties opened to the public, homes for employees and farmhouses. A buy-to-let company letting on the open market claims the rental business relief on the SDLT return and falls back to the higher rates. Companies holding a dwelling above the annual threshold may also be liable to the Annual Tax on Enveloped Dwellings, a separate yearly charge outside the scope of this page; the ${h.a('stamp-duty-company-purchase', 'company purchase guide')} explains both.</p>
<h3>Scotland and Wales</h3>
<p>Revenue Scotland charges the ADS on every dwelling a company buys, whether or not the company or its owners own anything else. The Welsh Revenue Authority applies the higher-rates table to company purchases from ${h.gbp(W.higher_min_price)}. The ${h.pct(S.corporate_flat_rate)} flat rate is an SDLT rule, so in Scotland and Wales the company’s bill is simply the surcharge bill shown in the table.</p>
<h2>Why a landlord cannot reclaim the surcharge</h2>
<p>The refund that home movers rely on is built around one idea: the new property replaces your main residence, and the surcharge only fell due because the old main residence had not sold yet. A rental is never your main residence, so buying one and later selling another rental, or even selling your own home, does not unlock a repayment of the surcharge on the rental. The ${h.gbp(h.tax({ nation: 'england', price: FLAT, situation: 'additional' }).surcharge)} added to a ${h.gbp(FLAT)} English flat is a permanent cost of the investment. Landlords sometimes see the word “refundable” in a calculator result and assume it applies to them; it applies only to a ${h.a('stamp-duty-moving-home', 'replacement of your home')}.</p>
<h2>Spouses, partners and joint landlords</h2>
<p>Married couples and civil partners who live together count as a single unit in England and Wales: if one spouse owns the family home and the other buys a flat to let in their sole name, the higher rates apply. Scotland goes further and treats cohabiting partners as part of the same economic unit for the ADS. When two friends or siblings buy a rental together, one of them owning a home is enough to put the whole purchase on the surcharge, not just that buyer’s share; the ${h.a('stamp-duty-joint-purchase', 'joint purchase calculator')} works through the combinations.</p>
<h2>Landlords based abroad</h2>
<p>A buyer who spent fewer than ${S.non_resident_days} days in the UK during the year before completion pays a further ${h.pct(S.non_resident_surcharge)} on every SDLT band in England and Northern Ireland, on top of the higher rates. On a ${h.gbp(300000)} rental that adds ${h.gbp(h.tax({ nation: 'england', price: 300000, situation: 'additional', nonResident: true }).nonResidentSurcharge)}. Scotland and Wales have no such charge, which can tilt the comparison for an expatriate investor. The ${h.a('non-resident-stamp-duty-surcharge', 'non-resident surcharge')} can be reclaimed if the buyer later meets the day count.</p>
<h2>Buying six or more flats at once</h2>
<p>A landlord acquiring a whole block in a single transaction in England or Northern Ireland can use the ${h.a('commercial-property-stamp-duty', 'non-residential table')} when it contains six or more dwellings, a route that has replaced multiple dwellings relief since 1 June 2024. On a ${h.gbp(1500000)} purchase that table gives ${h.gbp(h.t('england', 1500000, 'home', { kind: 'nonresidential' }))}, against ${h.gbp(h.t('england', 1500000, 'additional'))} at the residential higher rates.</p>`;
  },
});
