import { definePage } from '../../lib/page-types';
import { P, gbp, pct, t, compute } from '../../lib/kit';

const S = P.sdlt, L = P.lbtt, W = P.ltt;
const SUR = S.higher_rates_surcharge, MIN = S.higher_rates_min_price;
const HM = 300000;
const NAME = { england: 'England', scotland: 'Scotland', wales: 'Wales' } as const;
const cheapest = (p: number) => NAME[(['england', 'scotland', 'wales'] as const).reduce((a, b) => (t(b, p, 'additional') < t(a, p, 'additional') ? b : a))];

export default definePage({
  id: 'stamp-duty-second-home',
  group: 'england',
  order: 30,
  slug: 'stamp-duty-second-home',
  nav: 'Second homes: higher rates',
  card: `${pct(SUR)} more on every SDLT band once you own two dwellings: who counts, spouses, homes abroad and the refund.`,
  title: `Stamp Duty on a Second Home 2026: The ${pct(SUR)} Higher Rates`,
  description: `Stamp duty on a second home in 2026: ${pct(SUR)} extra on every SDLT band, so ${gbp(HM)} costs ${gbp(t('england', HM, 'additional'))}. Spouses, homes abroad, the ${gbp(MIN)} floor and the refund route.`,
  h1: 'Stamp duty on a second home or additional property',
  intro: 'The surcharge looks at what every buyer owns at midnight on completion day, anywhere in the world.',
  resume: `In England and Northern Ireland, a purchase that leaves any buyer owning more than one dwelling worth ${gbp(MIN)} or more at the end of completion day is taxed at the higher rates: ${pct(SUR)} added to every band of Stamp Duty Land Tax, the nil band included, since 31 October 2024 (${pct(S.previous.higher_rates_surcharge_before_31_october_2024)} before). A ${gbp(HM)} second home therefore costs ${gbp(t('england', HM, 'additional'))} instead of ${gbp(t('england', HM))}, the figure HMRC uses in its own guidance. Homes abroad count, a husband and wife count as one buyer, and one co-buyer with another property is enough to surcharge the whole price. There is no surcharge on a purchase under ${gbp(MIN)}, on mixed-use property, or when you replace your main home. Buy before you sell and you pay the higher rates first, then reclaim ${gbp(compute({ nation: 'england', price: HM, situation: 'additional' }).refundable)} on that ${gbp(HM)} purchase if the old home sells within ${S.replace_main_residence_years} years. Scotland charges an ${pct(L.ads_rate)} supplement on the whole price instead, ${gbp(compute({ nation: 'scotland', price: HM, situation: 'additional' }).surcharge)} here, and Wales a separate higher table.`,
  faqs: [
    { q: 'Does a holiday apartment I own in Spain make my UK purchase a second home?', a: `Yes. The test counts dwellings anywhere in the world, so an apartment in Spain worth ${gbp(MIN)} or more means a UK house bought while you keep it is an additional dwelling. Unless the UK house replaces your main residence, the ${pct(SUR)} higher rates apply. HMRC can open a check after completion, so tell your conveyancer about property abroad from the start.` },
    { q: 'My wife owns a buy-to-let flat in her sole name. Do I pay the higher rates if I buy a house alone?', a: `Yes, unless the two of you are separated. Married couples and civil partners are treated as one unit, so her flat counts as yours. A ${gbp(400000)} house bought in your name alone costs ${gbp(t('england', 400000, 'additional'))} rather than ${gbp(t('england', 400000))}, unless it replaces the main home you both live in.` },
    { q: `Will a ${gbp(30000)} fisherman’s hut I already own push my purchase into the higher rates?`, a: `Not if it is worth less than ${gbp(MIN)}. A dwelling under that value is ignored when counting what you own, and a purchase below ${gbp(MIN)} is never surcharged either. Valuation matters here: if the hut could fetch ${gbp(MIN)} or more on the open market, it counts as a dwelling and the new home is taxed at the higher rates.` },
    { q: 'Our new house completes before our old one sells. How long do we have to reclaim the surcharge?', a: `You must sell the previous main residence within ${S.replace_main_residence_years} years of buying the new one, then claim within ${S.refund_claim_months} months of the sale or of the filing date of the return, whichever is later. On a ${gbp(500000)} purchase the refund is ${gbp(compute({ nation: 'england', price: 500000, situation: 'additional' }).refundable)}. There is no refund if your spouse keeps a share of the old home.` },
    { q: 'Is a second home cheaper to buy in Wales or Scotland than in England?', a: `It depends on the price. At ${gbp(200000)} the bills are ${gbp(t('england', 200000, 'additional'))} in England, ${gbp(t('scotland', 200000, 'additional'))} in Scotland and ${gbp(t('wales', 200000, 'additional'))} in Wales; at ${gbp(600000)} they become ${gbp(t('england', 600000, 'additional'))}, ${gbp(t('scotland', 600000, 'additional'))} and ${gbp(t('wales', 600000, 'additional'))}. The cheapest nation is ${cheapest(200000)} at the lower price and ${cheapest(600000)} at the higher one. Scotland is the dearest at both, because its supplement is charged on every pound of the price rather than slice by slice.` },
  ],
  mini: 'secondHomeSurcharge',
  related: ['buy-to-let-stamp-duty', 'stamp-duty-moving-home', 'stamp-duty-surcharge-refund', 'additional-dwelling-supplement', 'ltt-higher-rates', 'stamp-duty-rates'],
  sources: ['govSdltHigher', 'fa2003', 'sdltmInherited', 'govSdltRefunds', 'rsAds', 'wraHigher'],
  body: (h) => {
    const s = h.P.sdlt, l = h.P.lbtt, w = h.P.ltt;
    const prices = [150000, 250000, 350000, 500000, 800000, 1200000];
    const cmp = prices.map((p) => [h.gbp(p), h.gbp(h.t('england', p)), h.gbp(h.t('england', p, 'additional')), h.gbp(h.t('scotland', p, 'additional')), h.gbp(h.t('wales', p, 'additional'))]);
    return `
<h2>The rule in one sentence</h2>
<p>Schedule 4ZA of the Finance Act 2003 asks a single question at the end of completion day: will any buyer own more than one dwelling worth ${h.gbp(s.higher_rates_min_price)} or more, without the new purchase replacing their main residence? If the answer is yes, every band of the SDLT scale rises by ${h.pct(s.higher_rates_surcharge)}, and the first slice of the price, normally free, starts at ${h.pct(s.residential[0][1] + s.higher_rates_surcharge)}.</p>
${h.bands('sdltHigher')}
<p>The label “second home” is misleading. The rule catches a buy-to-let bought by a landlord with one other flat, a pied-à-terre in London bought by a family who live in Kent, a house bought for a student child in a parent’s name, and a new main home bought before the old one is sold. It does not care how the property will be used, only how many dwellings the buyers will hold that night.</p>
<h2>Who is counted as owning a home</h2>
<h3>Spouses and civil partners form one unit</h3>
<p>A married couple or civil partners who are not separated are treated as a single buyer. If one of them owns a flat, the other cannot buy a home in their sole name at standard rates unless it replaces the couple’s main residence. Unmarried partners are assessed separately, so a cohabiting partner’s flat does not count against a buyer who is not on its title. The same purchase can therefore be taxed differently for a married couple and for an unmarried one.</p>
<h3>One co-buyer is enough</h3>
<p>When several people buy together, the purchase is surcharged if any one of them triggers the rule. A parent who owns their own house and joins a son or daughter on the title turns the whole purchase into a higher-rates transaction, not just the parent’s share. The ${h.a('stamp-duty-joint-purchase', 'joint purchase calculator')} sorts out which buyer decides the rate.</p>
<h3>Homes abroad, shares and inherited property</h3>
<p>A villa in Portugal or a flat in Lagos counts exactly like a house in Leeds. Part-ownership counts too, which surprises people who hold a small share of a family property. One exception softens the rule for inheritance: a share of ${h.pct(s.inherited_share_max)} or less, inherited together with a spouse, is ignored for ${s.inherited_years} years after the death (HMRC manual ${h.src('sdltmInherited', 'SDLTM09795')}). Larger inherited shares count immediately, as the ${h.a('inherited-property-stamp-duty', 'inherited property page')} explains.</p>
<h2>The ${h.gbp(s.higher_rates_min_price)} floor and other exclusions</h2>
<p>The threshold works in two directions. A purchase for less than ${h.gbp(s.higher_rates_min_price)} is never surcharged, whatever else you own. And a dwelling you already hold that is worth less than ${h.gbp(s.higher_rates_min_price)} is left out of the count. Two other cases fall outside the higher rates altogether: mixed-use property, such as a shop with a flat above, which follows the non-residential scale, and mobile homes.</p>
<p>Just above the floor, the surcharge applies to the whole price at once. At ${h.gbp(s.higher_rates_min_price)} an additional property costs ${h.gbp(h.t('england', s.higher_rates_min_price, 'additional'))}, while a pound less costs nothing, a jump worth knowing for anyone buying a cheap garage flat or a share of a seaside cottage.</p>
<h2>Buying before you sell</h2>
<p>A replacement of your main residence escapes the higher rates only when the old home is sold on or before the day the new one completes. If the chain breaks and you complete first, you will own two homes that night, and the conveyancer must file the return at the higher rates. The surcharge is not lost: if the former main residence is sold within ${s.replace_main_residence_years} years, HMRC refunds the difference between the higher and standard bills. The claim is due within ${s.refund_claim_months} months of the sale, or of the filing date of the original return if that is later.</p>
${h.breakdown({ nation: 'england', price: 425000, situation: 'additional' }, `Higher rates on a ${h.gbp(425000)} replacement home bought before the sale`)}
<p>In that example the buyer pays ${h.gbp(h.t('england', 425000, 'additional'))} at completion and can recover ${h.gbp(h.tax({ nation: 'england', price: 425000, situation: 'additional' }).refundable)} once the old house sells, leaving the standard ${h.gbp(h.t('england', 425000))}. Two conditions trip people up. No refund is due if a spouse or civil partner keeps a share of the old home, and HMRC allows extra time only in exceptional circumstances outside the buyer’s control, such as public authority restrictions on a sale. The ${h.a('stamp-duty-surcharge-refund', 'refund calculator')} sets out the deadlines from your completion date.</p>
<h2>Scotland and Wales charge it differently</h2>
<p>Scotland’s Additional Dwelling Supplement is not a band uplift. It is ${h.pct(l.ads_rate)} of the whole price for transactions from 5 December 2024, charged on top of ordinary LBTT from ${h.gbp(l.ads_min_price)}. The ownership test also reaches further: a married couple, civil partners or cohabiting partners, with their children under 16, form one economic unit. A replacement main home escapes ADS if the old one was sold within ${l.replace_main_residence_months} months before the purchase, and the refund window after the purchase is the same length (${h.a('additional-dwelling-supplement', 'how ADS works')}).</p>
<p>Wales uses a separate higher scale since 11 December 2024, starting at ${h.pct(w.higher[0][1])} on the first ${h.gbp(w.higher[0][0] as number)}, so a ${h.gbp(260000)} second home costs ${h.gbp(h.t('wales', 260000, 'additional'))}. The WRA gives two useful examples: a parent who co-buys with a child brings the higher rates, while a “joint borrower, sole proprietor” mortgage, where the parent borrows without owning, does not (${h.a('ltt-higher-rates', 'LTT higher rates')}).</p>
${h.table(['Price', 'England, one home', 'England, second home', 'Scotland with ADS', 'Wales higher rates'], cmp, 'Additional property bills across the three nations', ['l', 'r', 'r', 'r', 'r'])}
<p>The pattern in the table follows from the design. England adds a fixed number of points to each slice, Scotland adds a fixed share of the entire price, and Wales replaces its scale with a steeper one that starts lower. Scotland is the most expensive at every price shown. Between England and Wales the order flips: at ${h.gbp(250000)} Wales charges ${h.gbp(h.t('wales', 250000, 'additional'))} against ${h.gbp(h.t('england', 250000, 'additional'))} in England, while at ${h.gbp(800000)} the Welsh bill of ${h.gbp(h.t('wales', 800000, 'additional'))} is well above the English ${h.gbp(h.t('england', 800000, 'additional'))}, because the Welsh ${h.pct(w.higher[3][1])} band starts at ${h.gbp(w.higher[2][0] as number)}.</p>`;
  },
});
