import { definePage } from '../../lib/page-types';
import { P, gbp, pct, t, top, sdltPrevious } from '../../lib/kit';

const S = P.sdlt, V = S.previous;
const OLD3 = V.higher_rates_surcharge_before_31_october_2024;
const diffHome = t('england', 400000) - sdltPrevious(400000, 'home');
const ftbLoss = (p: number) => t('england', p, 'first') - sdltPrevious(p, 'first');
const maxFtbLoss = Math.max(...[425000, 450000, 500000, 550000, 600000, 625000].map(ftbLoss));

export default definePage({
  id: 'stamp-duty-changes-april-2025',
  group: 'england',
  order: 60,
  slug: 'stamp-duty-changes-april-2025',
  nav: 'What changed in April 2025',
  card: `Nil band down from ${gbp(top(V.residential, 0))} to ${gbp(top(S.residential, 0))}, first-time buyer relief cut, and the surcharges raised in October 2024.`,
  title: 'Stamp Duty Changes 2026: April 2025 Bands Before and After',
  description: `Stamp duty changes in force for 2026: the nil band fell to ${gbp(top(S.residential, 0))} on 1 April 2025, adding ${gbp(diffHome)} on a ${gbp(400000)} home. First-time buyers, surcharges, tables.`,
  h1: 'What changed in stamp duty on 1 April 2025',
  intro: 'A temporary cut came to an end, and two surcharges had already gone up five months earlier.',
  resume: `On 1 April 2025 the temporary Stamp Duty Land Tax thresholds introduced on 23 September 2022 ended in England and Northern Ireland. The nil band fell from ${gbp(top(V.residential, 0))} to ${gbp(top(S.residential, 0))}, with a new ${pct(S.residential[1][1])} band between ${gbp(top(S.residential, 0) + 1)} and ${gbp(top(S.residential, 1))}. For anyone paying standard rates on a price above ${gbp(top(S.residential, 1))}, the change adds exactly ${gbp(diffHome)}: a ${gbp(400000)} home went from ${gbp(sdltPrevious(400000, 'home'))} to ${gbp(t('england', 400000))}. First-time buyers lost more. Their nil band fell from ${gbp(top(V.first_time_buyer, 0))} to ${gbp(top(S.first_time_buyer, 0))} and the price ceiling from ${gbp(V.first_time_buyer_max_price)} to ${gbp(S.first_time_buyer_max_price)}, so the increase reaches ${gbp(maxFtbLoss)} at some prices. Two earlier changes took effect on 31 October 2024: the higher rates surcharge for additional dwellings rose from ${pct(OLD3)} to ${pct(S.higher_rates_surcharge)} on every band, and the company rate from ${pct(V.corporate_flat_rate_before_31_october_2024)} to ${pct(S.corporate_flat_rate)}. The Budget of 26 November 2025 left the April 2025 scale in place for 2026.`,
  faqs: [
    { q: 'We exchanged in March 2025 but completed in April. Which stamp duty rates applied?', a: `The April 2025 rates. SDLT is charged by reference to the effective date of the transaction, which for an ordinary purchase is completion, not exchange. A couple who exchanged on a ${gbp(350000)} house in March and completed in April paid ${gbp(t('england', 350000))} rather than ${gbp(sdltPrevious(350000, 'home'))}. The same logic applies to any future change of rates.` },
    { q: `Why did a first-time buyer at ${gbp(550000)} lose so much more than one at ${gbp(300000)}?`, a: `Because ${gbp(550000)} was inside the old relief and is now above the new ceiling. Before April 2025 the buyer paid ${gbp(sdltPrevious(550000, 'first'))}; now the whole price is taxed at standard rates, ${gbp(t('england', 550000, 'first'))}. At ${gbp(300000)} the bill stayed at ${gbp(t('england', 300000, 'first'))}, since that price sits within the nil band under both the old and new relief.` },
    { q: 'Did the stamp duty changes of 2025 also apply in Scotland and Wales?', a: `No. SDLT applies only in England and Northern Ireland. Scotland’s LBTT bands have been unchanged since 1 April 2021, although its Additional Dwelling Supplement rose to ${pct(P.lbtt.ads_rate)} on 5 December 2024. Wales kept its main LTT scale, in place since 10 October 2022, and introduced new higher rates on 11 December 2024.` },
    { q: `How much more does a buy-to-let landlord pay since the surcharge went to ${pct(S.higher_rates_surcharge)}?`, a: `On a ${gbp(250000)} flat, a landlord paid ${gbp(sdltPrevious(250000, 'additional', OLD3))} before 31 October 2024, ${gbp(sdltPrevious(250000, 'additional'))} between then and 31 March 2025, and ${gbp(t('england', 250000, 'additional'))} since 1 April 2025. The first rise came from the surcharge moving from ${pct(OLD3)} to ${pct(S.higher_rates_surcharge)}; the second from the lower nil band, which the surcharge sits on top of.` },
    { q: 'Will the old stamp duty thresholds come back in 2026?', a: `No return to them has been announced. The Budget of 26 November 2025 restated the bands that took effect on 1 April 2025, with a nil band of ${gbp(top(S.residential, 0))} and first-time buyer relief up to ${gbp(S.first_time_buyer_max_price)}. Any future change would be set by a Budget and legislation, and this site recalculates every figure from the published bands when that happens.` },
  ],
  mini: 'sdltApril2025',
  related: ['stamp-duty-rates', 'stamp-duty-first-time-buyer', 'stamp-duty-second-home', 'stamp-duty-company-purchase', 'stamp-duty-on-400000', 'sdlt-calculator'],
  sources: ['govSdltPrevious', 'govSdltRates', 'govSdltHigher', 'govSdltCorporate', 'ootlar2025'],
  body: (h) => {
    const s = h.P.sdlt, v = s.previous;
    const movers = [150000, 200000, 250000, 300000, 500000, 900000, 1500000].map((p) => [h.gbp(p), h.gbp(sdltPrevious(p, 'home')), h.gbp(h.t('england', p)), h.gbp(h.t('england', p) - sdltPrevious(p, 'home'))]);
    const ftb = [250000, 300000, 350000, 425000, 500000, 550000, 625000].map((p) => [h.gbp(p), h.gbp(sdltPrevious(p, 'first')), h.gbp(h.t('england', p, 'first')), h.gbp(ftbLoss(p))]);
    const add = [200000, 300000, 450000, 700000].map((p) => [h.gbp(p), h.gbp(sdltPrevious(p, 'additional', OLD3)), h.gbp(sdltPrevious(p, 'additional')), h.gbp(h.t('england', p, 'additional'))]);
    const corp = [600000, 1000000, 2000000].map((p) => [h.gbp(p), h.gbp(Math.floor(p * v.corporate_flat_rate_before_31_october_2024)), h.gbp(h.t('england', p, 'home', { company: true }))]);
    return `
<h2>Two dates, three changes</h2>
<p>The SDLT changes that shaped today’s bills arrived in two steps. On 31 October 2024 the surcharge for additional dwellings went from ${h.pct(OLD3)} to ${h.pct(s.higher_rates_surcharge)} on every band and the flat rate for companies buying expensive homes from ${h.pct(v.corporate_flat_rate_before_31_october_2024)} to ${h.pct(s.corporate_flat_rate)}. Then on 1 April 2025, the temporary thresholds set on 23 September 2022 expired as legislated, which lowered the nil band for everyone and shrank first-time buyer relief.</p>
<p>None of this was reversed later. The overview of tax legislation and rates published with the Budget of 26 November 2025 restates the April 2025 bands, and they are the ones applied throughout 2026.</p>
<h2>Home movers and single-home buyers</h2>
<p>For a buyer paying standard rates, the change sits entirely in the bottom of the scale. The old nil band ran to ${h.gbp(v.residential[0][0] as number)}; now only the first ${h.gbp(s.residential[0][0] as number)} is free and the next slice, up to ${h.gbp(s.residential[1][0] as number)}, is taxed at ${h.pct(s.residential[1][1])}. Above ${h.gbp(s.residential[1][0] as number)} the two scales are identical, so the extra cost stops growing.</p>
${h.table(['Portion of the price', 'Until 31 March 2025', 'From 1 April 2025'], [[`Up to ${h.gbp(s.residential[0][0] as number)}`, h.pct(v.residential[0][1]), h.pct(s.residential[0][1])], [`${h.gbp((s.residential[0][0] as number) + 1)} to ${h.gbp(s.residential[1][0] as number)}`, h.pct(v.residential[0][1]), h.pct(s.residential[1][1])], [`${h.gbp((s.residential[1][0] as number) + 1)} to ${h.gbp(s.residential[2][0] as number)}`, h.pct(v.residential[1][1]), h.pct(s.residential[2][1])], [`${h.gbp((s.residential[2][0] as number) + 1)} to ${h.gbp(s.residential[3][0] as number)}`, h.pct(v.residential[2][1]), h.pct(s.residential[3][1])], [`Above ${h.gbp(s.residential[3][0] as number)}`, h.pct(v.residential[3][1]), h.pct(s.residential[4][1])]], 'Standard residential bands, old and new', ['l', 'r', 'r'])}
${h.table(['Price', 'Before 1 April 2025', 'Since 1 April 2025', 'Increase'], movers, 'Standard rates at several prices', ['l', 'r', 'r', 'r'])}
<p>Read down the last column and the shape of the change appears: nothing at ${h.gbp(s.residential[0][0] as number)} or below, a rising cost up to ${h.gbp(s.residential[1][0] as number)}, then a flat ${h.gbp(h.t('england', 300000) - sdltPrevious(300000, 'home'))} for every price above. A family trading up from a ${h.gbp(500000)} house to a ${h.gbp(900000)} one pays the same increase as a couple buying a ${h.gbp(260000)} flat. In proportion to the price, the reform weighed most on homes between ${h.gbp(s.residential[0][0] as number)} and ${h.gbp(s.residential[1][0] as number)}, many of which paid nothing before.</p>
<h2>First-time buyers</h2>
<p>Relief for first-time buyers kept its two-band structure but on a smaller footprint. The nil band went from ${h.gbp(v.first_time_buyer[0][0] as number)} to ${h.gbp(s.first_time_buyer[0][0] as number)}, the ${h.pct(s.first_time_buyer[1][1])} band now stops at ${h.gbp(s.first_time_buyer_max_price)} instead of ${h.gbp(v.first_time_buyer_max_price)}, and the cliff where relief disappears moved down with it.</p>
${h.table(['Price', 'Before 1 April 2025', 'Since 1 April 2025', 'Increase'], ftb, 'First-time buyer bills, old and new relief', ['l', 'r', 'r', 'r'])}
<p>Three zones stand out. Up to ${h.gbp(s.first_time_buyer[0][0] as number)} nothing changed: the bill is still nil. Between ${h.gbp(s.first_time_buyer[0][0] as number)} and ${h.gbp(v.first_time_buyer[0][0] as number)}, buyers who used to pay nothing now pay ${h.pct(s.first_time_buyer[1][1])} on the slice above the new nil band. Between ${h.gbp(s.first_time_buyer_max_price)} and ${h.gbp(v.first_time_buyer_max_price)}, buyers fell out of the relief entirely and now pay standard rates on the whole price, which is where the largest increases sit. The ${h.a('stamp-duty-first-time-buyer', 'first-time buyer guide')} covers the conditions, which did not change.</p>
<h2>Second homes and buy-to-let</h2>
<p>Landlords and second-home buyers were hit twice. The surcharge rise of 31 October 2024 added ${h.pct(s.higher_rates_surcharge - OLD3)} on every band; the April 2025 nil band then added the same flat increase that movers pay, because the surcharge sits on top of the standard scale. The table follows three purchases through the three periods.</p>
${h.table(['Price', 'Before 31 Oct 2024', '31 Oct 2024 to 31 Mar 2025', 'Since 1 Apr 2025'], add, 'Higher rates for additional dwellings across three periods', ['l', 'r', 'r', 'r'])}
<p>At ${h.gbp(300000)}, the bill rose from ${h.gbp(sdltPrevious(300000, 'additional', OLD3))} to ${h.gbp(h.t('england', 300000, 'additional'))} in five months. The refund for buyers who complete before selling their old main home works as it did before, now on the larger surcharge (${h.a('stamp-duty-surcharge-refund', 'surcharge refund calculator')}).</p>
<h2>Companies</h2>
<p>The flat rate on dwellings bought by companies for more than ${h.gbp(s.corporate_flat_threshold)} without a relief rose by two points on 31 October 2024. Because it applies to the whole price, the increase grows in direct proportion to it.</p>
${h.table(['Price', `At ${h.pct(v.corporate_flat_rate_before_31_october_2024)}`, `At ${h.pct(s.corporate_flat_rate)}`], corp, 'Company rate on a dwelling, before and after 31 October 2024', ['l', 'r', 'r'])}
<p>A company that qualifies for a relief, such as a rental business letting to unconnected tenants, never pays the flat rate and was affected through the higher rates instead: the same two steps as a private landlord, first the larger surcharge in October 2024, then the lower nil band in April 2025. At ${h.gbp(600000)} with a relief, the company now pays ${h.gbp(h.t('england', 600000, 'home', { company: true, companyRelief: true }))}. The ${h.a('stamp-duty-company-purchase', 'company purchase guide')} sets out the reliefs.</p>
<h2>A chain that slipped past 31 March</h2>
<p>Consider a couple in Nottingham selling their flat and buying a ${h.gbp(285000)} semi, the only home they will own. Their completion was pencilled in for 28 March 2025 and slipped to 2 April after a delay further up the chain. Under the old scale the bill would have been ${h.gbp(sdltPrevious(285000, 'home'))}; on 2 April it was ${h.gbp(h.t('england', 285000))}. The contract, the price and the exchange date did not matter. The tax followed the completion date, which is the effective date of an ordinary purchase.</p>
${h.breakdown({ nation: 'england', price: 285000, situation: 'home' }, `The ${h.gbp(285000)} purchase under the scale in force since 1 April 2025`)}
<p>The breakdown shows where the extra money comes from: the slice between ${h.gbp(s.residential[0][0] as number)} and ${h.gbp(s.residential[1][0] as number)}, which used to be free and now costs ${h.gbp(Math.floor(((s.residential[1][0] as number) - (s.residential[0][0] as number)) * s.residential[1][1]))}. Everything above that slice is taxed exactly as before.</p>
<h2>Buyers who saw no change</h2>
<p>Not every purchase became dearer. A home at ${h.gbp(s.residential[0][0] as number)} or less still pays nothing at standard rates. A first-time buyer at ${h.gbp(s.first_time_buyer[0][0] as number)} or less still pays nothing. Purchases in Scotland and Wales were never covered by the change, since Land and Buildings Transaction Tax and Land Transaction Tax have their own scales. And commercial or mixed-use buyers, on the non-residential scale, saw no change on either date.</p>
<h2>Checking an older quote</h2>
<p>Figures prepared before April 2025 deserve a second look. Mortgage illustrations, estate agent cost sheets and moving budgets drawn up in 2024 used the old nil band, and a quote for an additional property prepared before 31 October 2024 used the ${h.pct(OLD3)} surcharge. For a purchase completing in 2026, recalculate with the current bands, and ask your conveyancer to confirm the figure before exchange, when the price can still be discussed.</p>
<h2>What stayed the same</h2>
<p>The ${h.pct(s.non_resident_surcharge)} non-resident surcharge, in force since 1 April 2021, did not move. Neither did the ${h.gbp(s.higher_rates_min_price)} floor below which the higher rates never apply, the non-residential scale, nor the ${s.return_days}-day deadline for the return and payment. The upper bands of the standard scale, at ${h.pct(s.residential[3][1])} and ${h.pct(s.residential[4][1])}, have the same thresholds as before. HMRC keeps the ${h.src('govSdltPrevious', 'rates for the period ending 31 March 2025')} online for transactions that completed under them; a return being amended for a purchase in that period still uses the old scale.</p>`;
  },
});
